# Production-like environment configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.production.yml up
version: '3.8'

services:
  frontend:
    # Override to use production build
    build:
      target: production
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Remove development volumes
      - /app/src
      - /app/public
      - /app/convex
    environment:
      - NODE_ENV=production
    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    # Remove development-specific settings
    stdin_open: false
    tty: false

  # Remove convex-dev service in production
  convex-dev:
    deploy:
      replicas: 0

  # Add production monitoring (optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: productivity-app-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - productivity-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: productivity-app-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - productivity-network
    profiles:
      - monitoring

volumes:
  prometheus-data:
  grafana-data: